name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Analizar con SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Validar SONAR_TOKEN
        run: |
          if [ -z "${{secrets.SONAR_TOKEN}}" ]; then
            echo "Error: SONAR_TOKEN no está definido."
            exit 1
          fi

      - name: Ejecutar análisis con SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.login=${{secrets.SONAR_TOKEN}}
